[General]

Background="backgrounds/bg.png"
font="fonts/Electroharmonix.otf"
Padding="50"
CornerRadius="8"
GeneralFontSize="14"
LoginScale="0.21"

LoginTitleColor="#1B5379"
LoginTitleSize="28"

FontFamily="../fonts/Electroharmonix.otf"
TextFieldColor="#FFFFFF"
TextFieldTextColor="#D7921F"
TextFieldBorderColor="#F8ECDD"
TextFieldBorderColorFocused="#FAE0B9"

LoginButtonTextColor="#FFFFFF"
LoginButtonBgColor="#D48E17"
LoginButtonText="Login"

PopupBgColor="#FFFFFF"
PopupHighlightColor="#F0E8D5"
PopupTextColor="#1B5379"

SessionButtonColor="#7c7f93"
SessionIconColor="#1e1d2f"

PowerButtonColor="#7c7f93"
PowerIconColor="#1e1d2f"

PlayerButtonColor="#FFFFFF"
PlayerIconColor="#1e1d2f"
PlayerTextColor="#FFFFFF"

DateColor="#FFFFFF"
DateSize="36"
DateIsBold="false"
DateOpacity="1"
DateFormat="dddd, MMMM d"

TimeColor="#FFFFFF"
TimeSize="16"
TimeIsBold="true"
TimeOpacity="0.8"
TimeFormat="hh:mm AP"
